#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  2 14:43:58 2021

@author: thayer
"""

import vtk
import sys
sys.path.append('/home/thayer/Desktop/DavidCS/ubuntu_partition/code/pydar/')
import pydar

# %% Test init

#project_path = 'D:\\mosaic_lidar\\Snow1\\'
project_path = '/media/thayer/Data/mosaic_lidar/Snow1/'

project_name = 'mosaic_01_040120.RiSCAN'

project = pydar.Project(project_path, project_name, read_scans=True)
print(project.project_date)

# %% try getting the port for singlescan

prt = project.scan_dict['ScanPos001'].get_polydata(port=True)

# %% Try getting port for merged points

prt = project.get_merged_points(port=True)

# %% try setting it as an input connection

t_filter = vtk.vtkTransformFilter()
t_filter.SetInputConnection(project.get_merged_points(port=True))
# That seg faults!
#t_filter.SetInputConnection(project.scan_dict['ScanPos001'].get_polydata(port=True))